use customer_behaviour;
select * from customer;
-- Q1:what is the total revenue generated by male vs.female customer?
select gender, sum(purchase_amount) as revenue
from customer group by gender;

-- Q2:which customers used a discount but still spent more the avg purchase amount?
select customer_id , purchase_amount from customer 
where discount_applied = "Yes" and 
purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3:which are the top 5 products with the highest avg review rating
select distinct(item_purchased),round(avg(review_rating),2) as "Average product rating" 
from customer 
group by item_purchased 
order by avg(review_rating) desc limit 5;

-- Q4:compare the avg purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2) as "Average purchase amount"
from customer 
where shipping_type in( "Express","Standard") 
group by shipping_type;

-- Q5:do subscribed customer spend more? compare avg spend and total revenue between subscribed and nonsubscribed
select subscription_status,
count(customer_id) as "total customer",
round(avg(purchase_amount),2) as "Avg_spend",
round(sum(purchase_amount),2) as "total_revenue" from customer
group by subscription_status
order by total_revenue desc;

-- Q6:which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = "Yes" then 1 else 0  end)/count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

-- Q7:segement customers into new,returning,and loyal based on their total number of 
-- previous purchases and show the count of each segement
with customer_type as(
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "Returning"
    else "Loyal"
    end as  customer_segement from customer
)
select customer_segement, count(*) as "Number of customer" 
from customer_type
group by customer_segement;

-- Q8:what are the top 3 most purchased products within each category?
with item_counts as(
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders 
from item_counts
where item_rank <= 3 ;

-- Q9:are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status;

-- Q10:what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as Revenue from customer 
group by age_group order by sum(purchase_amount) desc;